// This code is autogenerated by ImageTyped - do not modify

#if os(iOS)
import UIKit
#elseif os(OSX)
import AppKit
#endif

public enum ImageType: String {
{{with .EnumValues}}{{range .}}    case {{.Name}} = "{{.RawValue}}"
{{end}}{{end}}
}

#if os(iOS)
extension UIImage {
    public convenience init?(typed type: ImageType) {
        self.init(named: type.rawValue)
    }
}
#elseif os(OSX)
extension NSImage {
    public convenience init?(typed type: ImageType) {
        self.init(named: type.rawValue)
    }
}
#endif
