// This code is autogenerated by ImageTyped - do not modify

#if os(iOS)
import UIKit
#elseif os(OSX)
import AppKit
#endif

public enum ImageType: String {
{{with .EnumValues}}{{range .}}    case {{.Name}} = "{{.RawValue}}"
{{end}}{{end}}
}

#if os(iOS)
extension UIImage {
    public func imageTyped(type: ImageType) -> UIImage? {
        return UIImage(named: type.rawValue)
    }
}
#elseif os(OSX)
extension NSImage {
    public func imageTyped(type: ImageType) -> NSImage? {
        return NSImage(named: type.rawValue)
    }
}
#endif
